# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: portmapper.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'portmapper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10portmapper.proto\".\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\"\x1d\n\rRegisterReply\x12\x0c\n\x04port\x18\x01 \x01(\x05\"!\n\x11UnregisterRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\"!\n\x0fUnregisterReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x1e\n\x0eGetInfoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x0cGetInfoReply\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\"\x12\n\x10TerminateRequest\"3\n\x0eTerminateReply\x12!\n\x19registered_services_count\x18\x01 \x01(\x05\x32\xe7\x01\n\nPortMapper\x12\x35\n\x0fRegisterService\x12\x10.RegisterRequest\x1a\x0e.RegisterReply\"\x00\x12;\n\x11UnregisterService\x12\x12.UnregisterRequest\x1a\x10.UnregisterReply\"\x00\x12\x32\n\x0eGetServiceInfo\x12\x0f.GetInfoRequest\x1a\r.GetInfoReply\"\x00\x12\x31\n\tTerminate\x12\x11.TerminateRequest\x1a\x0f.TerminateReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portmapper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=66
  _globals['_REGISTERREPLY']._serialized_start=68
  _globals['_REGISTERREPLY']._serialized_end=97
  _globals['_UNREGISTERREQUEST']._serialized_start=99
  _globals['_UNREGISTERREQUEST']._serialized_end=132
  _globals['_UNREGISTERREPLY']._serialized_start=134
  _globals['_UNREGISTERREPLY']._serialized_end=167
  _globals['_GETINFOREQUEST']._serialized_start=169
  _globals['_GETINFOREQUEST']._serialized_end=199
  _globals['_GETINFOREPLY']._serialized_start=201
  _globals['_GETINFOREPLY']._serialized_end=244
  _globals['_TERMINATEREQUEST']._serialized_start=246
  _globals['_TERMINATEREQUEST']._serialized_end=264
  _globals['_TERMINATEREPLY']._serialized_start=266
  _globals['_TERMINATEREPLY']._serialized_end=317
  _globals['_PORTMAPPER']._serialized_start=320
  _globals['_PORTMAPPER']._serialized_end=551
# @@protoc_insertion_point(module_scope)
