# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapService = channel.unary_unary(
                '/Registry/MapService',
                request_serializer=registry__pb2.MapRequest.SerializeToString,
                response_deserializer=registry__pb2.MapReply.FromString,
                _registered_method=True)
        self.UnmapService = channel.unary_unary(
                '/Registry/UnmapService',
                request_serializer=registry__pb2.UnmapRequest.SerializeToString,
                response_deserializer=registry__pb2.UnmapReply.FromString,
                _registered_method=True)
        self.QueryService = channel.unary_unary(
                '/Registry/QueryService',
                request_serializer=registry__pb2.QueryRequest.SerializeToString,
                response_deserializer=registry__pb2.QueryReply.FromString,
                _registered_method=True)
        self.Finalize = channel.unary_unary(
                '/Registry/Finalize',
                request_serializer=registry__pb2.FinalizeRequest.SerializeToString,
                response_deserializer=registry__pb2.FinalizeReply.FromString,
                _registered_method=True)


class RegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MapService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnmapService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapService': grpc.unary_unary_rpc_method_handler(
                    servicer.MapService,
                    request_deserializer=registry__pb2.MapRequest.FromString,
                    response_serializer=registry__pb2.MapReply.SerializeToString,
            ),
            'UnmapService': grpc.unary_unary_rpc_method_handler(
                    servicer.UnmapService,
                    request_deserializer=registry__pb2.UnmapRequest.FromString,
                    response_serializer=registry__pb2.UnmapReply.SerializeToString,
            ),
            'QueryService': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryService,
                    request_deserializer=registry__pb2.QueryRequest.FromString,
                    response_serializer=registry__pb2.QueryReply.SerializeToString,
            ),
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=registry__pb2.FinalizeRequest.FromString,
                    response_serializer=registry__pb2.FinalizeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Registry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Registry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Registry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Registry/MapService',
            registry__pb2.MapRequest.SerializeToString,
            registry__pb2.MapReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnmapService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Registry/UnmapService',
            registry__pb2.UnmapRequest.SerializeToString,
            registry__pb2.UnmapReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Registry/QueryService',
            registry__pb2.QueryRequest.SerializeToString,
            registry__pb2.QueryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Registry/Finalize',
            registry__pb2.FinalizeRequest.SerializeToString,
            registry__pb2.FinalizeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
